### ISSUE TITLE
Check volumes folder after run back it is empty

### ISSUE THREAD

**Issue by zinating** [tlaanemaa/backup-docker#13]
I run docker with `-v /folername:/foldername`. And test when add new file in /foldername, in docker image also see it. But when run `backup-docker backup {docker-name}` then check `volumes` folder. I don't see any data in here.

**Comment by tlaanemaa** [comment]
Heya

That's probablly because the volume you're mounting is an unnamed one. By default those are not picked up in backups because they are often not explicitly created by the user (containers can create their own). There's a flag to change that behavior tho, try running with `--non-persistent-volumes`:
```
backup-docker backup {docker-name} --non-persistent-volumes
```

Edit: I just realised, what you're using is a bind mount. The backup only works on volumes not bind mounts. If you want to back up the bind mount then you can easily zip it yourself since it lives in your file system. Alternatively, create a a docker volume with `docker volume create [OPTIONS] [VOLUME]` and use that

More info on volume creation:
https://docs.docker.com/engine/reference/commandline/volume_create/

**Comment by tlaanemaa** [comment]
I'll close this as the question seems answered.
Feel free to let me know if you need further help tho.
