### ISSUE TITLE
Volumes are not being backed up

### ISSUE THREAD

**Issue by markov6** [tlaanemaa/backup-docker#30]
Hi, 

I'm starting grafana and influx containers with something like: 

`$ docker run -p 8086:8086 \
      -v influx-data:/var/lib/influxdb2 \
      influxdb:2.0`

Volume influxdb2 is not pre-created, hence it has following details, when I inspect it: 
`[
    {
        "CreatedAt": "2022-04-04T14:15:00+02:00",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/influx-data/_data",
        "Name": "influx-data",
        "Options": null,
        "Scope": "local"
    }
]`

And then this check determins it's not a persistent volume: 

`// Helper to detect non-persistent volumes
const isNonPersistentVolume = (inspect) => inspect.Labels == null && inspect.Options == null;`

I'm aware of the --non-persisten-volumes option, but that would gather too much garbage on the system, where I want to run my script. Is there a more reliable way to determine if a volume is persistent or not?

**Comment by tlaanemaa** [comment]
Hey

Since the volume isn't pre-created, like you said, then it seems like the tool worked correctly.
Volumes not being pre-created is the definition of a non-persistent volume I was going by when implementing this.

One way you could get around this is to run the script a second time targeting only that specific container and using the `--non-persistent-volumes` flags to backup all volumes on that specific container.
The command could look something like this:
```sh
backup-docker grafana --non-persistent-volumes
```

I hope this helps

**Comment by markov6** [comment]
Thanks a lot for the fast feedback, I knew I was missing something :)
